# Generated by Django 6.0.7 on 2026-07-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sr_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
