# Generated by Django 6.0.7 on 2026-07-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sr_no',
        ),
    ]
