# Generated by Django 6.0.7 on 2026-08-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_uploadhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='remark_file',
            field=models.FileField(blank=True, null=True, upload_to='remarks/'),
        ),
        migrations.AlterField(
            model_name='uploadhistory',
            name='file_hash',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
