# Generated by Django 6.0.7 on 2026-08-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_uploadhistory_remark_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadhistory',
            name='duplicate_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='failed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='total_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='uploaded_records',
            field=models.IntegerField(default=0),
        ),
    ]
